<?php
$container_list = array(
    'container' => __( 'Container', 'redux-framework-demo' ),
    'container-fliud'   => __( 'Container Fluid', 'redux-framework-demo' ),
    'container-fliud-spacing'     => __( 'Container Fluid With Padding', 'redux-framework-demo' ),
    'container-full'     => __( 'Full Width', 'redux-framework-demo' ),
);
$section_list = array(
    'banner' => 'Banner Section',
    'welcome' => 'Welcome Section',
    'service' => 'Service Section',
    'achievement' => 'Achievement Section',
    'whowe' => 'Who We Are',
    'pricing' => 'Pricing Section',
    'video' => 'Video Section',
    'blog' => 'Blog Section',
    'partner' => 'Partner Section',
    'gallery' => 'Gallery Section',
    'contact' => 'Contact Section',
    'team' => 'Team Member',  
    'widgets' => 'Widget Section',
    'button' => 'Linking Section',      
    'blank' => 'Blank Section',      
);
$animations = array(
    'Attention Seekers' => array(
        'bounce' => 'bounce',
        'flash' => 'flash',
        'pulse' => 'pulse',
        'rubberBand' => 'rubberBand',
        'shake' => 'shake',
        'swing' => 'swing',
        'tada' => 'tada',
        'wobble' => 'wobble',
        'jello' => 'jello',
        'rotate' => 'rotate',
    ),
    'Bouncing Entrances' => array(
        'bounceIn' => 'bounceIn',
        'bounceInDown' => 'bounceInDown',
        'bounceInLeft' => 'bounceInLeft',
        'bounceInRight' => 'bounceInRight',
        'bounceInUp' => 'bounceInUp',
    ),
    'Fading Entrances' => array(
		'fadeIn' => 'fadeIn',
		'fadeInDown' => 'fadeInDown',
		'fadeInDownBig' => 'fadeInDownBig',
		'fadeInLeft' => 'fadeInLeft',
		'fadeInLeftBig' => 'fadeInLeftBig',
		'fadeInRight' => 'fadeInRight',
		'fadeInRightBig' => 'fadeInRightBig',
		'fadeInUp' => 'fadeInUp',
		'fadeInUpBig' => 'fadeInUpBig',
    ),
    'Flippers' => array(
		'flip' => 'flip',
		'flipInX' => 'flipInX',
		'flipInY' => 'flipInY',
    ),
    'Lightspeed' => array(
		'lightSpeedIn' => 'lightSpeedIn',
    ),
    'Rotating Entrances' => array(
		'rotateIn' => 'rotateIn',
		'rotateInDownLeft' => 'rotateInDownLeft',
		'rotateInDownRight' => 'rotateInDownRight',
		'rotateInUpLeft' => 'rotateInUpLeft',
		'rotateInUpRight' => 'rotateInUpRight',
    ),
    'Sliding Entrances' => array(
		'slideInUp' => 'slideInUp',
		'slideInDown' => 'slideInDown',
		'slideInLeft' => 'slideInLeft',
		'slideInRight' => 'slideInRight',
    ),
    'Zoom Entrances' => array(
		'zoomIn' => 'zoomIn',
		'zoomInDown' => 'zoomInDown',
		'zoomInLeft' => 'zoomInLeft',
		'zoomInRight' => 'zoomInRight',
		'zoomInUp' => 'zoomInUp',
    ),
    'Specials' => array(
		'jackInTheBox' => 'jackInTheBox',
		'rollIn' => 'rollIn',
    ),
);
$bootstrap_grids = array(
    'col-lg-2' => 'col-lg-2',
    'col-lg-3' => 'col-lg-3',
    'col-lg-4' => 'col-lg-4',
    'col-lg-5' => 'col-lg-5',
    'col-lg-6' => 'col-lg-6',
    'col-lg-7' => 'col-lg-7',
    'col-lg-8' => 'col-lg-8',
    'col-lg-9' => 'col-lg-9',
    'col-lg-10' => 'col-lg-10',
    'col-lg-11' => 'col-lg-11',
    'col-lg-12' => 'col-lg-12',
    'col-md-2' => 'col-md-2',
    'col-md-3' => 'col-md-3',
    'col-md-4' => 'col-md-4',
    'col-md-5' => 'col-md-5',
    'col-md-6' => 'col-md-6',
    'col-md-7' => 'col-md-7',
    'col-md-8' => 'col-md-8',
    'col-md-9' => 'col-md-9',
    'col-md-10' => 'col-md-10',
    'col-md-11' => 'col-md-11',
    'col-md-12' => 'col-md-12',
    'col-sm-2' => 'col-sm-2',
    'col-sm-3' => 'col-sm-3',
    'col-sm-4' => 'col-sm-4',
    'col-sm-5' => 'col-sm-5',
    'col-sm-6' => 'col-sm-6',
    'col-sm-7' => 'col-sm-7',
    'col-sm-8' => 'col-sm-8',
    'col-sm-9' => 'col-sm-9',
    'col-sm-10' => 'col-sm-10',
    'col-sm-11' => 'col-sm-11',
    'col-sm-12' => 'col-sm-12',
    'col-xs-2' => 'col-xs-2',
    'col-xs-3' => 'col-xs-3',
    'col-xs-4' => 'col-xs-4',
    'col-xs-5' => 'col-xs-5',
    'col-xs-6' => 'col-xs-6',
    'col-xs-7' => 'col-xs-7',
    'col-xs-8' => 'col-xs-8',
    'col-xs-9' => 'col-xs-9',
    'col-xs-10' => 'col-xs-10',
    'col-xs-11' => 'col-xs-11',
    'col-xs-12' => 'col-xs-12'
);
$col_ratio = array(
    '1' => '100%',
    '2' => '75% + 25%',
    '3' => '66% + 33%',
    '4' => '50% + 50%',
    '5' => '33% + 66%',
    '6' => '25% + 75%',

    '7' => '33% + 33% + 33%',
    '8' => '50% + 25% + 25%',
    '9' => '25% + 50% + 25%',
    '10' => '25% + 25% + 50%',
    
    '11' => '25% + 25% + 25% + 25%',
);